# Generated by Django 5.1.7 on 2025-03-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('summary', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('hits', models.BigIntegerField(default=0)),
            ],
        ),
    ]
